"use client";
import { useMemo, useState } from "react";
import { money } from "@/lib/utils";
import { causeLabel } from "./LogList";
import { useSession } from "./SessionProvider";
import { useModalA11y } from "@/lib/use-modal-a11y";
import Field from "./Field";

const today = () => new Date().toISOString().slice(0, 10);

// Everything the report shows for one date+location scope.
function buildReport(entries, date, locId) {
  const rows = entries.filter((e) => e.date === date && (locId === "all" || e.locationId === locId));
  const cash = rows.filter((e) => e.kind === "cash");
  const scratch = rows.filter((e) => e.kind === "scratch");
  const inv = rows.filter((e) => e.kind === "inventory");
  const flagged = rows.filter((e) =>
    ["open", "under-review"].includes(e.varianceStatus) || ["open", "under-review"].includes(e.disputeStatus));
  const verified = rows.filter((e) => e.verifiedBy).length;
  const totals = {
    sales: cash.reduce((s, e) => s + (e.sales || 0), 0),
    paidout: cash.reduce((s, e) => s + (e.paidout || 0), 0),
    counted: cash.reduce((s, e) => s + (e.counted || 0), 0),
    diff: cash.reduce((s, e) => s + (e.diff || 0), 0),
    scratchDollars: scratch.reduce((s, e) => s + (e.dollars || 0), 0),
  };
  return { rows, cash, scratch, inv, flagged, verified, totals };
}

export default function ReportModal({ entries, locations, locName, onClose, onToast }) {
  const { profile, vendor } = useSession();
  const [date, setDate] = useState(today());
  const [locId, setLocId] = useState("all");
  const [busy, setBusy] = useState(false);
  const panelRef = useModalA11y(onClose);

  const r = useMemo(() => buildReport(entries, date, locId), [entries, date, locId]);
  const locLabel = locId === "all" ? "All locations" : locName(locId);
  const fileSlug = `eod-${vendor.slug}-${locId === "all" ? "all" : locName(locId).replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-${date}`;

  async function downloadPdf() {
    setBusy(true);
    try {
      // ~0.5 MB library — loaded only when a report is actually generated.
      const { pdf, Document, Page, Text, View, StyleSheet } = await import("@react-pdf/renderer");
      const s = StyleSheet.create({
        page: { padding: 28, fontSize: 9, fontFamily: "Helvetica", color: "#1a1c2e" },
        h1: { fontSize: 15, fontFamily: "Helvetica-Bold", marginBottom: 2 },
        meta: { color: "#666", marginBottom: 2 },
        section: { fontSize: 11, fontFamily: "Helvetica-Bold", marginTop: 14, marginBottom: 5 },
        row: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#ccc", paddingVertical: 3 },
        head: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#1a1c2e", paddingVertical: 3, fontFamily: "Helvetica-Bold" },
        totals: { flexDirection: "row", paddingVertical: 4, fontFamily: "Helvetica-Bold", borderTopWidth: 1, borderTopColor: "#1a1c2e" },
        neg: { color: "#b03a3a" }, pos: { color: "#2f7d5b" },
        sig: { flexDirection: "row", justifyContent: "space-between", marginTop: 34 },
        sigLine: { width: "44%", borderTopWidth: 1, borderTopColor: "#1a1c2e", paddingTop: 3, fontSize: 8, color: "#666" },
        empty: { marginTop: 8, color: "#666", fontStyle: "italic" },
      });
      const C = ({ w, children, style }) => (
        <Text style={[{ width: w }, ...(Array.isArray(style) ? style : style ? [style] : [])]}>{children}</Text>
      );
      const doc = (
        <Document title={fileSlug}>
          <Page size="A4" style={s.page}>
            <Text style={s.h1}>{vendor.name} — End of Day Report</Text>
            <Text style={s.meta}>Store code: {vendor.slug} · {locLabel} · {date}</Text>
            <Text style={s.meta}>Generated by {profile.name} at {new Date().toLocaleString()}</Text>

            {r.rows.length === 0 && <Text style={s.empty}>No activity recorded for this date and location.</Text>}

            {r.cash.length > 0 && (<>
              <Text style={s.section}>Cash drawers</Text>
              <View style={s.head}><C w="14%">Drawer</C><C w="8%">Shift</C><C w="14%">By</C><C w="10%">Start</C><C w="10%">Sales</C><C w="10%">Paid out</C><C w="10%">Expected</C><C w="10%">Counted</C><C w="9%">Over/short</C><C w="5%">Blind</C></View>
              {r.cash.map((e, i) => (
                <View key={i} style={s.row}>
                  <C w="14%">{e.drawerName || "—"}</C><C w="8%">{e.shift}</C><C w="14%">{e.by}{e.verifiedBy ? ` ✓${e.verifiedBy}` : ""}</C>
                  <C w="10%">{money(e.start)}</C><C w="10%">{money(e.sales)}</C><C w="10%">{money(e.paidout)}</C>
                  <C w="10%">{money(e.expected)}</C><C w="10%">{money(e.counted)}</C>
                  <C w="9%" style={e.diff < -0.005 ? s.neg : e.diff > 0.005 ? s.pos : null}>{e.diff >= 0 ? "+" : ""}{money(e.diff)}</C>
                  <C w="5%">{e.blind ? "yes" : ""}</C>
                </View>
              ))}
              <View style={s.totals}><C w="46%">Totals</C><C w="10%">{money(r.totals.sales)}</C><C w="10%">{money(r.totals.paidout)}</C><C w="10%"> </C><C w="10%">{money(r.totals.counted)}</C>
                <C w="9%" style={r.totals.diff < -0.005 ? s.neg : r.totals.diff > 0.005 ? s.pos : null}>{r.totals.diff >= 0 ? "+" : ""}{money(r.totals.diff)}</C><C w="5%"> </C></View>
            </>)}

            {r.scratch.length > 0 && (<>
              <Text style={s.section}>Scratch-offs</Text>
              <View style={s.head}><C w="22%">Game</C><C w="14%">Pack</C><C w="10%">Price</C><C w="16%">Start → End</C><C w="10%">Sold</C><C w="12%">Dollars</C><C w="16%">By</C></View>
              {r.scratch.map((e, i) => (
                <View key={i} style={s.row}>
                  <C w="22%">{e.game}</C><C w="14%">{e.pack || "—"}</C><C w="10%">{money(e.price)}</C>
                  <C w="16%">#{e.startno} → #{e.endno}</C><C w="10%">{e.sold}</C><C w="12%">{money(e.dollars)}</C>
                  <C w="16%">{e.by}{e.verifiedBy ? ` ✓` : ""}</C>
                </View>
              ))}
              <View style={s.totals}><C w="62%">Total scratch-off dollars</C><C w="38%">{money(r.totals.scratchDollars)}</C></View>
            </>)}

            {r.inv.length > 0 && (<>
              <Text style={s.section}>Inventory counts</Text>
              <View style={s.head}><C w="22%">Item</C><C w="8%">Shift</C><C w="10%">Start</C><C w="10%">Received</C><C w="10%">Sold</C><C w="10%">Removed</C><C w="10%">Expected</C><C w="10%">Counted</C><C w="10%">Diff</C></View>
              {r.inv.map((e, i) => (
                <View key={i} style={s.row}>
                  <C w="22%">{e.itemName}</C><C w="8%">{e.shift}</C><C w="10%">{e.startQty}</C><C w="10%">{e.received}</C>
                  <C w="10%">{e.soldQty}</C><C w="10%">{e.removed}</C><C w="10%">{e.expected}</C><C w="10%">{e.counted}</C>
                  <C w="10%" style={e.diff < 0 ? s.neg : e.diff > 0 ? s.pos : null}>{e.diff >= 0 ? "+" : ""}{e.diff}</C>
                </View>
              ))}
            </>)}

            {r.flagged.length > 0 && (<>
              <Text style={s.section}>Flagged &amp; disputed</Text>
              {r.flagged.map((e, i) => (
                <View key={i} style={s.row}>
                  <C w="30%">{e.kind === "cash" ? e.drawerName : e.kind === "inventory" ? e.itemName : e.game} ({e.by})</C>
                  <C w="25%">{["open", "under-review"].includes(e.varianceStatus) ? `variance ${e.varianceStatus}` : ""}</C>
                  <C w="20%">{["open", "under-review"].includes(e.disputeStatus) ? `dispute ${e.disputeStatus}` : ""}</C>
                  <C w="25%">{e.causeCode ? `${causeLabel(e.causeCode)}${e.causeNote ? ` — ${e.causeNote}` : ""}` : ""}</C>
                </View>
              ))}
            </>)}

            <Text style={s.section}>Verification</Text>
            <Text>{r.verified} of {r.rows.length} entries verified by a manager.</Text>

            <View style={s.sig}>
              <View style={s.sigLine}><Text>Prepared by · date</Text></View>
              <View style={s.sigLine}><Text>Reviewed by (manager) · date</Text></View>
            </View>
          </Page>
        </Document>
      );
      const blob = await pdf(doc).toBlob();
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = `${fileSlug}.pdf`;
      a.click();
      URL.revokeObjectURL(a.href);
    } catch (err) {
      console.error(err);
      onToast?.("PDF failed — try the Print button");
    }
    setBusy(false);
  }

  // Print-friendly HTML fallback (browser print -> PDF).
  function printReport() {
    const esc = (x) => String(x ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;");
    const w = window.open("", "_blank", "width=800,height=900");
    if (!w) return onToast?.("Allow pop-ups to print");
    const cashRows = r.cash.map((e) => `<tr><td>${esc(e.drawerName)}</td><td>${esc(e.shift)}</td><td>${esc(e.by)}</td><td>${money(e.start)}</td><td>${money(e.sales)}</td><td>${money(e.paidout)}</td><td>${money(e.expected)}</td><td>${money(e.counted)}</td><td>${e.diff >= 0 ? "+" : ""}${money(e.diff)}</td><td>${e.blind ? "yes" : ""}</td><td>${esc(e.verifiedBy || "")}</td></tr>`).join("");
    const scratchRows = r.scratch.map((e) => `<tr><td>${esc(e.game)}</td><td>${esc(e.pack)}</td><td>${money(e.price)}</td><td>#${e.startno} → #${e.endno}</td><td>${e.sold}</td><td>${money(e.dollars)}</td><td>${esc(e.by)}</td></tr>`).join("");
    const invRows = r.inv.map((e) => `<tr><td>${esc(e.itemName)}</td><td>${esc(e.shift)}</td><td>${e.startQty}</td><td>${e.received}</td><td>${e.soldQty}</td><td>${e.removed}</td><td>${e.expected}</td><td>${e.counted}</td><td>${e.diff >= 0 ? "+" : ""}${e.diff}</td></tr>`).join("");
    w.document.write(`<!doctype html><title>${esc(fileSlug)}</title>
      <style>body{font:12px Helvetica,Arial;margin:32px;color:#1a1c2e}h1{font-size:18px;margin:0}p{color:#666;margin:2px 0}
      h2{font-size:13px;margin:18px 0 6px}table{width:100%;border-collapse:collapse;font-size:11px}
      th,td{text-align:left;padding:3px 6px;border-bottom:1px solid #ccc}th{border-bottom:2px solid #1a1c2e}
      .sig{display:flex;justify-content:space-between;margin-top:48px}.sig div{width:44%;border-top:1px solid #1a1c2e;padding-top:4px;font-size:10px;color:#666}</style>
      <h1>${esc(vendor.name)} — End of Day Report</h1>
      <p>Store code: ${esc(vendor.slug)} · ${esc(locLabel)} · ${esc(date)}</p>
      <p>Generated by ${esc(profile.name)} at ${new Date().toLocaleString()}</p>
      ${r.rows.length === 0 ? "<p><i>No activity recorded for this date and location.</i></p>" : ""}
      ${r.cash.length ? `<h2>Cash drawers</h2><table><tr><th>Drawer</th><th>Shift</th><th>By</th><th>Start</th><th>Sales</th><th>Paid out</th><th>Expected</th><th>Counted</th><th>Over/short</th><th>Blind</th><th>Verified</th></tr>${cashRows}<tr><th colspan="4">Totals</th><th>${money(r.totals.sales)}</th><th>${money(r.totals.paidout)}</th><th></th><th>${money(r.totals.counted)}</th><th>${r.totals.diff >= 0 ? "+" : ""}${money(r.totals.diff)}</th><th></th><th></th></tr></table>` : ""}
      ${r.scratch.length ? `<h2>Scratch-offs</h2><table><tr><th>Game</th><th>Pack</th><th>Price</th><th>Tickets</th><th>Sold</th><th>Dollars</th><th>By</th></tr>${scratchRows}</table>` : ""}
      ${r.inv.length ? `<h2>Inventory counts</h2><table><tr><th>Item</th><th>Shift</th><th>Start</th><th>Received</th><th>Sold</th><th>Removed</th><th>Expected</th><th>Counted</th><th>Diff</th></tr>${invRows}</table>` : ""}
      <h2>Verification</h2><p>${r.verified} of ${r.rows.length} entries verified by a manager.</p>
      <div class="sig"><div>Prepared by · date</div><div>Reviewed by (manager) · date</div></div>`);
    w.document.close();
    w.focus();
    w.print();
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onClick={onClose}>
      <div ref={panelRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="report-modal-title"
        className="bg-surface rounded-2xl shadow-xl w-full max-w-md max-h-[90vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="px-4 py-3.5 border-b border-line flex items-center justify-between">
          <h2 id="report-modal-title" className="font-semibold text-[15px]">End-of-day report</h2>
          <button className="btn-ghost text-[13px] px-2.5 py-1" onClick={onClose} aria-label="Close"><span aria-hidden="true">✕</span></button>
        </div>
        <div className="p-4 space-y-3.5">
          <div className="grid grid-cols-2 gap-3">
            <Field label="Date">
              <input type="date" className="input" value={date} onChange={(e) => setDate(e.target.value)} /></Field>
            <Field label="Location">
              <select className="input" value={locId} onChange={(e) => setLocId(e.target.value)}>
                <option value="all">All locations</option>
                {locations.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}
              </select></Field>
          </div>

          <div className="bg-panel border border-line rounded-xl p-3.5 text-sm space-y-1">
            <div className="text-[11px] uppercase tracking-wide text-muted font-semibold mb-1.5">Will include</div>
            <div>{r.cash.length} cash counts · net {r.totals.diff >= 0 ? "+" : ""}{money(r.totals.diff)}</div>
            <div>{r.scratch.length} scratch-off counts · {money(r.totals.scratchDollars)}</div>
            <div>{r.inv.length} inventory counts</div>
            <div>{r.flagged.length} flagged / disputed</div>
            <div>{r.verified} of {r.rows.length} verified</div>
          </div>

          <div className="flex gap-2">
            <button className="btn-primary flex-1" disabled={busy} onClick={downloadPdf}>
              {busy ? "Generating…" : "Download PDF"}
            </button>
            <button className="btn-ghost flex-1" onClick={printReport}>Print</button>
          </div>
        </div>
      </div>
    </div>
  );
}
